### ISSUE TITLE
Will not compile for me

### ISSUE THREAD

**Issue by EQWorry** [Danya0x07/tm1637-simple-library#1]
Hi, thanks you for this simple library! I am not experienced C user, but trying to compile the code I stumble upon the following. Any chance at correcting my mistakes? :-) Thanks!

```
root@Hills:~/Install/tm1637-simple-library-master# cc -Wall tm1637.c -o tm1637
In file included from tm1637.c:7:
tm1637.c: In function ‘transmission_check_ack’:
tm1637_port.h:31:29: error: expected identifier before ‘(’ token
 #define _us_timer_get()     (0xFF)
                             ^
tm1637.c:81:30: note: in expansion of macro ‘_us_timer_get’
     while (_din_is_high() && _us_timer_get() < 10) {}
                              ^~~~~~~~~~~~~
```

**Comment by EQWorry** [comment]
Well, I see now the files are not intended to compile in their raw state, they provide only basic methods and need to be worked on. Maybe you could add a demo application that would actually use the simple library? (If I am not mistaken, that would mean adding initialization calls and such...)

**Comment by Danya0x07** [comment]
Hi, thanks for your feedback. I wrote this library while working on [that](https://github.com/Danya0x07/DawnAlarm)  project.
There you can find a usage example (./lib).
I write my libraries in a such style to be cross-platform and framework independent.
Good luck!

**Comment by Danya0x07** [comment]
All the initialization for the TM1637 is to correctly setup your GPIOs, and then you can call any function of this library. If the module doesn't show you anything, try to call `tm1637_set_brightness()` with non-zero value.

**Comment by EQWorry** [comment]
Thank you very much! Now I understand the point of the library much better. And after adjusting the code to my specific needs everything is running smoothly. Thanks again!
